fix pipeline

diff --git a/.github/workflows/report_ingestion.yml b/.github/workflows/report_ingestion.yml
--- a/.github/workflows/report_ingestion.yml
+++ b/.github/workflows/report_ingestion.yml
@@ -1,129 +1,131 @@
-name: ReportIngestion
-on:
-  # Manual
-  
-  # schedule:
-  #   - cron: '00 05 * * *'
+# Pipeline not used. Kept for reference
 
-  workflow_dispatch:
-    inputs:
-      environment:
-        required: true
-        type: choice
-        description: Select the Environment
-        options:
-          - uat
-          - prod
-        default: prod
-
-      notify:
-        description: 'notify report results'
-        required: false
-        type: boolean
-        default: true
-
-      month_report:
-        required: true
-        type: choice
-        description: Select the month report
-        options:
-          - 1
-          - 2
-          - 3
-          - 4
-          - 5
-          - 6
-          - 7
-          - 8
-          - 9
-          - 10
-          - 11
-          - 12
-        default: '7'        
-
-permissions:
-  id-token: write
-  contents: read
-  deployments: write
-
-
-jobs:
-  create_runner:
-    name: Create Runner
-    runs-on: ubuntu-22.04
-    environment:
-      name: ${{(github.event.inputs == null && 'prod') || inputs.environment }}
-    outputs:
-      runner_name: ${{ steps.create_github_runner.outputs.runner_name }}
-    steps:
-      - name: Create GitHub Runner
-        id: create_github_runner
-        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-create-action
-        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-create-action@main
-        with:
-          client_id: ${{ secrets.CD_CLIENT_ID }}
-          tenant_id: ${{ secrets.TENANT_ID }}
-          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
-          container_app_environment_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_NAME }}
-          resource_group_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_RESOURCE_GROUP_NAME }} # RG of the runner
-          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
-          self_hosted_runner_image_tag: "latest"
-
-  report_script:
-    needs: [ create_runner ]
-    name: Report ${{(github.event.inputs == null && 'prod') || inputs.environment }}
-    runs-on: [ self-hosted, "${{ needs.create_runner.outputs.runner_name }}" ]
-    environment: ${{(github.event.inputs == null && 'prod') || inputs.environment }}
-    steps:
-
-      - name: Checkout
-        id: checkout
-        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
-
-      - name: Login
-        id: login
-        # from https://github.com/Azure/login/commits/master
-        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
-        with:
-          client-id: ${{ secrets.CLIENT_ID }}
-          tenant-id: ${{ secrets.TENANT_ID }}
-          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
-
-      - name: Run reports
-        shell: bash
-        run: |
-          export BIZ_COSMOS_KEY=${{ secrets.BIZ_COSMOS_KEY }}
-          export MONTH_SELECTED=${{ inputs.month_report}}
-
-          cd ./report
-          chmod +x ./run.sh
-          ./run.sh local
-
-      # - name: Send notification to Slack
-      #   id: slack
-      #   if: ${{ (success() || failure()) && (github.event.inputs == null || inputs.notify)}}
-      #   uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
-      #   with:
-      #     payload-file-path: "./report/src/report.json"
-      #   env:
-      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_REPORT }}
-      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-
-  cleanup_runner:
-    name: Cleanup Runner
-    needs: [ create_runner, report_script ]
-    if: ${{ always() }}
-    runs-on: ubuntu-22.04
-    environment: ${{(github.event.inputs == null && 'uat') || inputs.environment }}
-    steps:
-      - name: Cleanup GitHub Runner
-        id: cleanup_github_runner
-        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-cleanup-action
-        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-cleanup-action@0ee2f58fd46d10ac7f00bce4304b98db3dbdbe9a
-        with:
-          client_id: ${{ secrets.CD_CLIENT_ID }}
-          tenant_id: ${{ secrets.TENANT_ID }}
-          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
-          resource_group_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_RESOURCE_GROUP_NAME }}
-          runner_name: ${{ needs.create_runner.outputs.runner_name }}
-          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
+#name: ReportIngestion
+#on:
+#  # Manual
+#
+#  # schedule:
+#  #   - cron: '00 05 * * *'
+#
+#  workflow_dispatch:
+#    inputs:
+#      environment:
+#        required: true
+#        type: choice
+#        description: Select the Environment
+#        options:
+#          - uat
+#          - prod
+#        default: prod
+#
+#      notify:
+#        description: 'notify report results'
+#        required: false
+#        type: boolean
+#        default: true
+#
+#      month_report:
+#        required: true
+#        type: choice
+#        description: Select the month report
+#        options:
+#          - 1
+#          - 2
+#          - 3
+#          - 4
+#          - 5
+#          - 6
+#          - 7
+#          - 8
+#          - 9
+#          - 10
+#          - 11
+#          - 12
+#        default: '7'
+#
+#permissions:
+#  id-token: write
+#  contents: read
+#  deployments: write
+#
+#
+#jobs:
+#  create_runner:
+#    name: Create Runner
+#    runs-on: ubuntu-22.04
+#    environment:
+#      name: ${{(github.event.inputs == null && 'prod') || inputs.environment }}
+#    outputs:
+#      runner_name: ${{ steps.create_github_runner.outputs.runner_name }}
+#    steps:
+#      - name: Create GitHub Runner
+#        id: create_github_runner
+#        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-create-action
+#        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-create-action@main
+#        with:
+#          client_id: ${{ secrets.CD_CLIENT_ID }}
+#          tenant_id: ${{ secrets.TENANT_ID }}
+#          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
+#          container_app_environment_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_NAME }}
+#          resource_group_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_RESOURCE_GROUP_NAME }} # RG of the runner
+#          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
+#          self_hosted_runner_image_tag: "latest"
+#
+#  report_script:
+#    needs: [ create_runner ]
+#    name: Report ${{(github.event.inputs == null && 'prod') || inputs.environment }}
+#    runs-on: [ self-hosted, "${{ needs.create_runner.outputs.runner_name }}" ]
+#    environment: ${{(github.event.inputs == null && 'prod') || inputs.environment }}
+#    steps:
+#
+#      - name: Checkout
+#        id: checkout
+#        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
+#
+#      - name: Login
+#        id: login
+#        # from https://github.com/Azure/login/commits/master
+#        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
+#        with:
+#          client-id: ${{ secrets.CLIENT_ID }}
+#          tenant-id: ${{ secrets.TENANT_ID }}
+#          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
+#
+#      - name: Run reports
+#        shell: bash
+#        run: |
+#          export BIZ_COSMOS_KEY=${{ secrets.BIZ_COSMOS_KEY }}
+#          export MONTH_SELECTED=${{ inputs.month_report}}
+#
+#          cd ./report
+#          chmod +x ./run.sh
+#          ./run.sh local
+#
+#      # - name: Send notification to Slack
+#      #   id: slack
+#      #   if: ${{ (success() || failure()) && (github.event.inputs == null || inputs.notify)}}
+#      #   uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
+#      #   with:
+#      #     payload-file-path: "./report/src/report.json"
+#      #   env:
+#      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_REPORT }}
+#      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#
+#  cleanup_runner:
+#    name: Cleanup Runner
+#    needs: [ create_runner, report_script ]
+#    if: ${{ always() }}
+#    runs-on: ubuntu-22.04
+#    environment: ${{(github.event.inputs == null && 'uat') || inputs.environment }}
+#    steps:
+#      - name: Cleanup GitHub Runner
+#        id: cleanup_github_runner
+#        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-cleanup-action
+#        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-cleanup-action@0ee2f58fd46d10ac7f00bce4304b98db3dbdbe9a
+#        with:
+#          client_id: ${{ secrets.CD_CLIENT_ID }}
+#          tenant_id: ${{ secrets.TENANT_ID }}
+#          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
+#          resource_group_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_RESOURCE_GROUP_NAME }}
+#          runner_name: ${{ needs.create_runner.outputs.runner_name }}
+#          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
